version: '3'
services:
  nginx:
    image: mikops/my-nginx-repo:latest
    container_name: nginx-for-task
    ports:
      - "8081:80"
      - "443:443"
    restart: always
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf

      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

